// Public entry of the topic-registry package.
//
// Composed of two blocks:
//   1) `./index.generated` — auto-generated by scripts/build.mjs from
//      event contracts under `src/domains/`. Contains `registry`, `Topic`,
//      `TopicPayloads`, `TOPICS`.
//   2) `./shared-types` — hand-written cross-cutting types (CartItem,
//      MenuItem, ...) that event payloads and MFE UI code both depend on.
//
// NOTE: the template's original comment said "do not edit". We do edit — to
// keep contracts + shared payload/model types co-located in one package for
// the demo. See docs/content/guides/demo-architecture.md § Contracts.

export * from "./index.generated.js";
export * from "./shared-types.js";
