// Public entry of the topic-registry package.
//
// Composed of two blocks:
//   1) `./index.generated` — auto-generated by scripts/build.mjs from
//      event contracts under `src/domains/`. Contains `registry`, `Topic`,
//      `TopicPayloads`, `TOPICS`.
//   2) `./shared-types` — hand-written cross-cutting types (CartItem,
//      MenuItem, ...) that event payloads and MFE UI code both depend on.
//
// NOTE: the template's original comment said "do not edit". We do edit — to
// keep contracts + shared payload/model types co-located in one package for
// the demo. See docs/content/guides/demo-architecture.md § Contracts.

export * from "./index.generated.js";
export * from "./shared-types.js";

// Request/response type re-exports. Request contracts declare their input
// as `payload` (picked up automatically by TopicPayloads) and their output
// as a named `*Response` type — sender code imports these to type the
// `bus.request<...>()` call site.
export type { CartAddItemResponse } from "./domains/cart/add-item.v1.js";
export type { CartDecrementResponse } from "./domains/cart/decrement.v1.js";
export type { CartRemoveItemResponse } from "./domains/cart/remove-item.v1.js";
export type { CheckoutStartResponse } from "./domains/checkout/start.v1.js";
