/**
 * Topic kinds — what a topic *is*, declared once in its contract instead of
 * decided at every call site.
 *
 * - `event`   — a fact ("order paid"), fan-out to current subscribers via `emit()`.
 * - `request` — a command to one recipient that answers, via `request()`.
 * - `state`   — a current value ("cart has two items"); the runtime keeps
 *               the last one and hands it to every new subscriber.
 */
export type TopicKind = 'event' | 'request' | 'state';

/** The runtime's view: `initBroker({ topics: TOPIC_KINDS })`. */
export type TopicKindMap = Readonly<Record<string, TopicKind>>;

/**
 * Per-topic kind and answer type, as generated by `@hedwigjs/create-registry`
 * (`TopicContracts`). Third parameter of `createClient<T, P, C>`. Every
 * entry is optional, and an entry without `kind` — or no map at all — keeps
 * both verbs open, so untyped code keeps compiling.
 */
export type TopicContractsMap<T extends string> = {
  readonly [K in T]?: { readonly kind?: TopicKind; readonly response?: unknown };
};

/** The declared kind of `K`, or the full union when the contract does not say. */
export type KindOf<C, K> = K extends keyof C
  ? NonNullable<C[K]> extends { kind: infer Kd extends TopicKind }
    ? Kd
    : TopicKind
  : TopicKind;

/** Topics `emit()` accepts: events and state (and anything of unknown kind). */
export type EmitTopic<T extends string, C> = {
  [K in T]: 'event' extends KindOf<C, K> ? K : 'state' extends KindOf<C, K> ? K : never;
}[T];

/** Topics `request()` accepts: requests (and anything of unknown kind). */
export type RequestTopic<T extends string, C> = {
  [K in T]: 'request' extends KindOf<C, K> ? K : never;
}[T];

/** The answer type declared for request `K`; `Fallback` when unknown. */
export type ResponseOf<C, K, Fallback = unknown> = K extends keyof C
  ? NonNullable<C[K]> extends { response: infer R }
    ? [R] extends [never]
      ? Fallback
      : R
    : Fallback
  : Fallback;
